version: '3'

services:
  users-service:
    build:
      context: .
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - postgres
    ports:
      - '3001:3001'

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: